---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root

  vars:
    mongodb_version: "3.4"
    mongodb_net_bindip: 0.0.0.0

  roles:
    - geerlingguy.repo-epel
    - greendayonfire.mongodb

  tasks:
    - name: download node script
      get_url: url=https://rpm.nodesource.com/setup_9.x dest=/tmp/node_installer.sh

    - name: Run script to install node repo
      script: /tmp/node_installer.sh

    - name: Install nodejs package
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - net-tools
        - telnet

    - name: Install npm global modules
      npm:
        name: "{{ item }}"
        global: yes
        state: present
      with_items:
        - create-react-app
        - nodemon
  
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root

  roles:
    - ocha.yarn
    